const GET_THREADS = 'GET_THREADS';
const GET_THREADS_SUCCESS = 'GET_THREADS_SUCCESS';
const GET_THREADS_FAIL = 'GET_THREADS_FAIL';

const CREATE_THREAD = 'CREATE_THREAD';
const CREATE_THREAD_SUCCESS = 'CREATE_THREAD_SUCCESS';
const CREATE_THREAD_FAIL = 'CREATE_THREAD_FAIL';

const threads = {
  GET_THREADS,
  GET_THREADS_SUCCESS,
  GET_THREADS_FAIL,
  CREATE_THREAD,
  CREATE_THREAD_SUCCESS,
  CREATE_THREAD_FAIL
};

export default threads;
