const GET_THREAD = 'GET_THREAD';
const GET_THREAD_SUCCESS = 'GET_THREAD_SUCCESS';
const GET_THREAD_FAIL = 'GET_THREAD_FAIL';

const CREATE_THREAD = 'CREATE_THREAD';
const CREATE_THREAD_SUCCESS = 'CREATE_THREAD_SUCCESS';
const CREATE_THREAD_FAIL = 'CREATE_THREAD_FAIL';

const thread = {
  GET_THREAD,
  GET_THREAD_SUCCESS,
  GET_THREAD_FAIL,
  CREATE_THREAD,
  CREATE_THREAD_SUCCESS,
  CREATE_THREAD_FAIL
};

export default thread;
